### ISSUE TITLE
Reactor 3 integration?

### ISSUE THREAD

**Issue by brandonlamb** [noboomu/proteus#1]
Any plans to implement reactive? Jooby has a module (although based on Reactor 2.5).

I added this for Reactor 3, curious if something similar is possible with proteus?

```kotlin
    fun reactor(): Route.Mapper<Any> = Route.Mapper.create("reactor") { value ->
      when (value) {
        is Mono<*> -> Deferred { deferred ->
          value
            .doOnError { deferred.reject(it) }
            .doOnCancel { deferred.reject(Exception("cancelled")) }
            .subscribe { deferred.resolve(it) }
        }
        else -> value
      }
    }
  }
```

**Comment by brandonlamb** [comment]
btw, I like the usage of JAX-RS API for re-use, which also helps migration a bit if like us you are coming from Java EE

**Comment by noboomu** [comment]
Sorry for the delay! 
Definitely want to get reactive this in there somehow. 
I'd like to do it via JDK 9 rather than something from Spring, they always seem to bloat the hell out of everything...

Glad you appreciate the JAX-RS, trying to be as neutral as possible :)
