### ISSUE TITLE
bindInterceptor cannot work

### ISSUE THREAD

**Issue by easykoala** [noboomu/proteus#11]
hi，
bindInterceptor(Matchers.any(), Matchers.annotatedWith(Names.named("log")), new LoggerMethodInterceptor());

    @Named("log")
    public String get() {
        return "hello";
    }

**Comment by noboomu** [comment]
Can you share some code or provide some more details? Not sure what you are asking.

**Comment by noboomu** [comment]
I'm closing until I get some more details. Please feel free to reopen.
