### ISSUE TITLE
Registering a Service with its own thread

### ISSUE THREAD

**Issue by ratcashdev** [noboomu/proteus#14]
Is it possible to register a Service that will spawn/use its own thread? As I see it the supported BaseService is using the `AbstractIdleService` which, according to the javadoc can't use its own thread.
Alternatively, if Proteus does not support this, is it possible to get to Undertow's builder? The idea is to poll messages from a queue (hence the thread that constantly checks for messages) and feeding it to undertow's websockets.

**Comment by noboomu** [comment]
Added possible fix in https://github.com/noboomu/proteus/commit/14b3a54426bdb9ff90f146a9d3ee23f1d5f650c2. You could also simply manage your own threads inside the ```BaseService``` so long as they are terminated when ```shutdown()``` is called. I'll leave this open until you can confirm the commit resolves the issue.

**Comment by ratcashdev** [comment]
Thanks, works. You can close this.
BTW: any chance of extending the API to also allow registering websocket handlers?

**Comment by noboomu** [comment]
Was planning on it at some point. I'll start now.

**Comment by ratcashdev** [comment]
@noboomu just a heads-up:
http://lists.jboss.org/pipermail/undertow-dev/2019-April/002318.html
Maybe it would be faster to directly port this to netty :D
