### ISSUE TITLE
How to configure openapi?

### ISSUE THREAD

**Issue by easykoala** [noboomu/proteus#18]
http://localhost:8090/v1/openapi

Fetch error
Not Found http://localhost:8090/v1/openapi.yaml

**Comment by noboomu** [comment]
Make sure that you have added the OpenAPIService to the main application:

```
ProteusApplication app = new ProteusApplication();
app.addService(OpenAPIService.class);
```

Let me know if that does it.

**Comment by easykoala** [comment]
yes, in proteus-example-master: 
 ExampleApplication app = new ExampleApplication();

        app.addService(AssetsService.class);

        app.addService(io.sinistral.proteus.openapi.services.OpenAPIService.class);

**Comment by noboomu** [comment]
I updated the example project. Give it a shot now please.

**Comment by easykoala** [comment]
In new example：
http://localhost:8090/v1/openapi

in console：

09:47:12.511 [XNIO-1 task-1] ERROR io.sinistral.proteus.server.handlers.ServerDefaultResponseListener - 
	message: Not Found
	path: /swagger-ui.css
java.lang.Exception: Not Found
	at io.sinistral.proteus.server.handlers.ServerDefaultResponseListener.handleDefaultResponse(ServerDefaultResponseListener.java:62)
	at io.undertow.server.HttpServerExchange.endExchange(HttpServerExchange.java:1608)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:389)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
09:48:12.711 [XNIO-1 I/O-5] DEBUG io.undertow.request - Timing out idle connection from /127.0.0.1:62878

**Comment by easykoala** [comment]
in OpenAPIService.java:
at line 310:
  String pathTemplate = this.applicationPath + File.separator + this.specFilename;
changed to:
  String pathTemplate = this.applicationPath + "/" + this.specFilename;

It's OK, run on windows :), but Where is the swagger-ui.css?  
  <link href="/v1/openapi/swagger-ui.css" rel="stylesheet">

**Comment by noboomu** [comment]
Sorry, I believe you need to add the AssetsService as well. Try doing that please.

**Comment by easykoala** [comment]
In application.conf:

assets {
  # the base path assets will be server from
  path = "/openapi"

/openapi/swagger-ui.css can access, but /v1/openapi/swagger-ui.css cannot.

In AssetsService.java:
at 52 line：
       final String assetsPath = serviceConfig.getString("path");
Should be changed to below: ???
      final String assetsPath = applicationPath + serviceConfig.getString("path");

**Comment by noboomu** [comment]
Can you please try the example project from a fresh pull and let me know if the css loads. I cannot verify the problem. The assets path specifies which directory to serve static content from. What are you trying to accomplish? That might be an easier start :)

**Comment by noboomu** [comment]
Closing for now. Let me know if it's still an issue.
