### ISSUE TITLE
Support cors?

### ISSUE THREAD

**Issue by easykoala** [noboomu/proteus#19]
How to do?

**Comment by noboomu** [comment]
You can add CORS headers globally in the config file:
```
globalHeaders 
{
   Access-Control-Allow-Origin: "*"
   Access-Control-Allow-Methods: "*"
   Access-Control-Allow-Headers: "*"
   Server = ${application.name}
}
```

Or you can create a a class that extends `HandlerWrapper` and use the `@Chain` annotation on a controller or it's methods.
