### ISSUE TITLE
How to use the web session?

### ISSUE THREAD

**Issue by easykoala** [noboomu/proteus#21]
Put some values into session like springmvc? Thanks.

**Comment by noboomu** [comment]
Underneath proteus is still Undertow. There are a countless ways to handle session storage. However, the main goal was stateless performance so you will need to refer to http://undertow-io.github.io/undertow-io-site/documentation/undertow-design-doc.html. Let me know if you have any implementation questions :)

**Comment by easykoala** [comment]
e.g. memory， JWT or redis session.
Which JWT implementation is better？
Another question :)
   SesionWrapper class implemented session, How can I controll its timeout?

**Comment by easykoala** [comment]
e.g. memory， JWT or redis session.
Which JWT implementation is better？
Another question :)
   SesionWrapper class implemented session, How can I controll its timeout?

**Comment by noboomu** [comment]
I personally like JWT over redis as it reduces  the burden on the server. Not sure about the session timeout, you could look at the Pac4j project though.
