### ISSUE TITLE
Something wrong with POM

### ISSUE THREAD

**Issue by alexspetty** [noboomu/proteus#22]
I get this when I run the quickstart:

> $ /bin/bash -e <(curl -fsSL https://raw.githubusercontent.com/noboomu/proteus-example/master/scripts/quickStart.sh)
Cloning into 'proteus-example'...
Warning: Permanently added the RSA host key for IP address '{removed}' to the list of known hosts.
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 226 (delta 0), reused 10 (delta 0), pack-reused 208
Receiving objects: 100% (226/226), 441.58 KiB | 4.80 MiB/s, done.
Resolving deltas: 100% (52/52), done.
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< io.sinistral:proteus-example >--------------------
[INFO] Building proteus-example 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.328 s
[INFO] Finished at: 2019-08-30T14:08:10-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project proteus-example: Could not resolve dependencies for project io.sinistral:proteus-example:jar:1.0.0: Failed to collect dependencies at io.sinistral:proteus-core:jar:0.4.1: Failed to read artifact descriptor for io.sinistral:proteus-core:jar:0.4.1: Failure to find io.sinistral:proteus-project:pom:0.4.1 in https://oss.sonatype.org/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of oss-sonatype has elapsed or updates are forced

**Comment by noboomu** [comment]
I just redeployed 0.4.1. Try removing any cached versions in your maven repo and try again. Let me know if it doesn't work.

**Comment by alexspetty** [comment]
This is still not working for me: I am seeing this:
--
First clearing cache:
--
`alex@blackhole9:~/src/proteus-example$ mvn dependency:purge-local-repository
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< io.sinistral:proteus-example >--------------------
[INFO] Building proteus-example 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:purge-local-repository (default-cli) @ proteus-example ---
[INFO] Failure detected.
[INFO] Unable to resolve all dependencies for : io.sinistral:proteus-core:0.4.1. Falling back to non-transitive mode for initial artifact resolution.
Downloading from oss-sonatype: https://oss.sonatype.org/content/groups/public/io/sinistral/proteus-core/0.4.1/proteus-core-0.4.1.pom
Downloaded from oss-sonatype: https://oss.sonatype.org/content/groups/public/io/sinistral/proteus-core/0.4.1/proteus-core-0.4.1.pom (9.9 kB at 24 kB/s)
Downloading from oss-sonatype: https://oss.sonatype.org/content/groups/public/io/sinistral/proteus-openapi/0.4.1/proteus-openapi-0.4.1.pom
Downloaded from oss-sonatype: https://oss.sonatype.org/content/groups/public/io/sinistral/proteus-openapi/0.4.1/proteus-openapi-0.4.1.pom (4.2 kB at 37 kB/s)
Downloading from oss-sonatype: https://oss.sonatype.org/content/groups/public/org/pac4j/undertow-pac4j/3.0.0-SNAPSHOT/undertow-pac4j-3.0.0-20181121.064952-6.pom
Downloaded from oss-sonatype: https://oss.sonatype.org/content/groups/public/org/pac4j/undertow-pac4j/3.0.0-SNAPSHOT/undertow-pac4j-3.0.0-20181121.064952-6.pom (6.5 kB at 64 kB/s)
Downloading from oss-sonatype: https://oss.sonatype.org/content/groups/public/org/pac4j/pac4j-oauth/3.4.0/pac4j-oauth-3.4.0.pom
Downloaded from oss-sonatype: https://oss.sonatype.org/content/groups/public/org/pac4j/pac4j-oauth/3.4.0/pac4j-oauth-3.4.0.pom (2.7 kB at 26 kB/s)
Downloading from oss-sonatype: https://oss.sonatype.org/content/groups/public/io/sinistral/proteus-core/0.4.1/proteus-core-0.4.1.jar
Downloaded from oss-sonatype: https://oss.sonatype.org/content/groups/public/io/sinistral/proteus-core/0.4.1/proteus-core-0.4.1.jar (169 kB at 897 kB/s)
Downloading from oss-sonatype: https://oss.sonatype.org/content/groups/public/io/sinistral/proteus-openapi/0.4.1/proteus-openapi-0.4.1.jar
Downloaded from oss-sonatype: https://oss.sonatype.org/content/groups/public/io/sinistral/proteus-openapi/0.4.1/proteus-openapi-0.4.1.jar (55 kB at 353 kB/s)
Downloading from oss-sonatype: https://oss.sonatype.org/content/groups/public/org/pac4j/undertow-pac4j/3.0.0-SNAPSHOT/undertow-pac4j-3.0.0-20181121.064952-6.jar
Downloaded from oss-sonatype: https://oss.sonatype.org/content/groups/public/org/pac4j/undertow-pac4j/3.0.0-SNAPSHOT/undertow-pac4j-3.0.0-20181121.064952-6.jar (21 kB at 175 kB/s)
Downloading from oss-sonatype: https://oss.sonatype.org/content/groups/public/org/pac4j/pac4j-oauth/3.4.0/pac4j-oauth-3.4.0.jar
Downloaded from oss-sonatype: https://oss.sonatype.org/content/groups/public/org/pac4j/pac4j-oauth/3.4.0/pac4j-oauth-3.4.0.jar (246 kB at 1.7 MB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.317 s
[INFO] Finished at: 2019-09-11T16:34:20-04:00
[INFO] ------------------------------------------------------------------------`
--
Then rebuilding:
--
`alex@blackhole9:~/src/proteus-example$ mvn package exec:exec
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< io.sinistral:proteus-example >--------------------
[INFO] Building proteus-example 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from oss-sonatype: https://oss.sonatype.org/content/groups/public/org/pac4j/undertow-pac4j/3.0.0-SNAPSHOT/maven-metadata.xml
Downloaded from oss-sonatype: https://oss.sonatype.org/content/groups/public/org/pac4j/undertow-pac4j/3.0.0-SNAPSHOT/maven-metadata.xml (1.2 kB at 2.7 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.894 s
[INFO] Finished at: 2019-09-11T16:34:31-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project proteus-example: Could not resolve dependencies for project io.sinistral:proteus-example:jar:1.0.0: Failed to collect dependencies at io.sinistral:proteus-core:jar:0.4.1: Failed to read artifact descriptor for io.sinistral:proteus-core:jar:0.4.1: Failure to find io.sinistral:proteus-project:pom:0.4.1 in https://oss.sonatype.org/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of oss-sonatype has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`

**Comment by noboomu** [comment]
:)
