### ISSUE TITLE
How to get request post json data？

### ISSUE THREAD

**Issue by easykoala** [noboomu/proteus#24]
hi，:)

POST http://localhost:8080/api/user/login

playload
{"username":"admin","password":"111111"}

server:
   public ServerResponse<Map<String,Object>> login(ServerRequest request)

How to get json data?

**Comment by noboomu** [comment]
Please try the following:
 ```java
@POST
@Path("/login")
public ServerResponse<Map<String,Object>> login(ServerRequest request, @BeanParam Map<String,Object> payload) {
System.out.println("login request: " + payload.toString());
return response(payload).applicationJson();
}```
