### ISSUE TITLE
How to get url parameters into a bean？

### ISSUE THREAD

**Issue by easykoala** [noboomu/proteus#25]
get http://localhost:8090/v1/examples/user?name=tom&birth=1990-10-28

into User：
  private String name;
  private Date birth;

 public void reguser(ServerRequest request, @BeanParam User user) {

Another question：
   using @GET and @POST in same method？

    @GET
    @POST
    @Path("/user")
    @Produces({MediaType.APPLICATION_JSON})
    public void mybatis2(ServerRequest request, @BeanParam User user) {

**Comment by noboomu** [comment]
I'd recommend making separate methods for the get and post requests. From my understanding, they are effectively two different endpoints. They can share the same path however, which should give you what you want.

If you are trying to create a user named `tom` with birthdate `1990-10-28` (my birthday by the way) you probably want to create a post or put endpoint with two query parameters.

Using put:
```java
@PUT
@Operation(description = "Register a user")
@Path("/user")
@Produces({MediaType.APPLICATION_JSON})
public ServerResponse<User> customer(   ServerRequest request, @QueryParam("name") String name,  @QueryParam("birth") Date birth  )   {

      User user = new User();
      user.setName(name);
      user.setBirth(birth);
      user.save();

      return io.sinistral.proteus.server.ServerResponse.response(user);

}
```
Using post:
```java

// Example User class, use whatever you need instead
class User {
        private String name;
        private Date birth;

        public String getName()
        {
            return name;
        }

        public void setName(String name)
        {
            this.name = name;
        }

        public Date getBirth()
        {
            return birth;
        }

        public void setBirth(Date birth)
        {
            this.birth = birth;
        }
}

@POST
@Operation(description = "Register a user")
@Path("/user")
@Produces({MediaType.APPLICATION_JSON})
@Consumes({MediaType.APPLICATION_JSON})
public ServerResponse<User> customer(   ServerRequest request, @BeanParam User user  )   {

      User newUser = new User();
      newUser.setName(user.getName());
      newUser.setBirth(user.getBirth());
      newUser.save();

      return io.sinistral.proteus.server.ServerResponse.response(newUser);

}
```
