### ISSUE TITLE
io.sinistral:proteus-project pom cannot be found in Maven repository

### ISSUE THREAD

**Issue by soberaionima** [noboomu/proteus#27]
Trying to build a project with the following dependency:
        <dependency>
            <groupId>io.sinistral</groupId>
            <artifactId>proteus-core</artifactId>
            <version>0.4.2</version>
        </dependency>

build is failed with the error: Could not resolve dependencies for project io.sinistral:proteus-example:jar:1.0.0: Failed to collect dependencies at io.sinistral:proteus-core:jar:0.4.2: Failed to read artifact descriptor for io.sinistral:proteus-core:jar:0.4.2: Could not find artifact io.sinistral:proteus-project:pom:0.4.2 in maven (https://repo1.maven.org/maven2/) -> [Help 1]

**Comment by noboomu** [comment]
Just released 0.4.3. Might take a few hours to propagate but should solve your problem. 0.4.3-SNAPSHOT will work now though.

**Comment by soberaionima** [comment]
Still does not work with release version.

`[ERROR] Failed to execute goal on project proteus-example: Could not resolve dependencies for project io.sinistral:proteus-example:jar:1.0.0: Failed to collect dependencies at io.sinistral:proteus-core:jar:0.4.3: Failed to read artifact descriptor for io.sinistral:proteus-core:jar:0.4.3: Failure to find io.sinistral:proteus-project:pom:0.4.3 in https://oss.sonatype.org/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of oss-sonatype has elapsed or updates are forced -> [Help 1]
`

Seems like proteus-project.pom has not been published into Maven for release build

**Comment by soberaionima** [comment]
works on version 0.4.5. thanks for fix!

**Comment by noboomu** [comment]
Thanks for bringing it to my attention!
