### ISSUE TITLE
Can I map the controller to root '/'  ？

### ISSUE THREAD

**Issue by easykoala** [noboomu/proteus#30]
Can I map the controller to root '/' ？
http://localhost:8080/

**Comment by noboomu** [comment]
Yes, to do so you just need to set the path to "" in the application section of the conf file. 

```
application {
path = ""
}
```

**Comment by easykoala** [comment]
http://localhost:8080/v1/ can access，
but http://localhost:8080/v1 can not access，404 error
:)
