### ISSUE TITLE
How to implement Oauth2 (social) authorisation for endpoints?

### ISSUE THREAD

**Issue by sixman9** [noboomu/proteus#7]
**I'd like to use social logins such as Facebook and Google to authorise access to my JAX-RS endpoints.**

Any ideas how I could do this within Proteus?

**Comment by noboomu** [comment]
There are a number of ways to pull that off. I'll try and add a few examples to the example project in the next few days. Definitely feasible.

**Comment by sixman9** [comment]
As a starter for 10, a StackOverflow user, [Cassio Mazzochi-Molin][1] posted Java code for an **[Oauth2-enabled annotation implementation][2], specifically for JAX-RS**. 

It would be great if that code could be adapted to also offer several social login backends, e.g. Facebook, Google etc. (might the ['Scribe' Java library][scribe] also be helpful?).

Your thoughts?


[1]: https://stackoverflow.com/users/1426227/cassio-mazzochi-molin

[2]: https://stackoverflow.com/questions/33824798/using-google-signin-for-web-sites-in-a-java-application/33826058#33826058

[scribe]: https://github.com/scribejava/scribejava

**Comment by noboomu** [comment]
You could definitely try Pac4J as they have a module for Undertow.  In my work projects I usually have a controller for oauth processing. One endpoint to retrieve the authorization url and another to handle the callback from the provider. Keeping track of the user after that point is up to the implementation. Proteus strives to be as un-opinionated as possible and focused solely on performance. What goes on between the request and response in the controller is up to you :) As I said above, I will try and get a simple example up asap.

**Comment by noboomu** [comment]
Closing this as sample will be live shortly.
